FROM nginx:alpine

RUN rm -rf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# Alterado para adicionar o caminho do sistema
RUN mkdir /var/www/html -p && \
    touch /var/www/html/index.php